---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jamming
  namespace: haugom
  labels:
    app: jamming
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jamming
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jamming
    spec:
      containers:
      - name: jamming
        image: quay.io/haugom/jamming:{{ .app_tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "24Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
