---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .hostname }}
    nginx.ingress.kubernetes.io/upstream-vhost: $service_name.$namespace.svc.cluster.local
  name: jamming
spec:
  tls:
    - hosts:
      - {{ .hostname }}
      secretName: tls-jamming
  rules:
    - host: {{ .hostname }}
      http:
        paths:
        - path: /
          backend:
            serviceName: jamming
            servicePort: 80
