---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: jamming
  namespace: haugom
spec:
  secretName: tls-jamming
  issuerRef:
    name: letsencrypt-prod
  commonName: jamming.k8s.cloud.haugom.org
  dnsNames:
  - jamming.k8s.cloud.haugom.org
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - jamming.k8s.cloud.haugom.org
    - http01:
        ingress: my-ingress
      domains:
      - jamming.k8s.cloud.haugom.org
