---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: jamming
  namespace: haugom
spec:
  secretName: tls-jamming
  issuerRef:
    name: letsencrypt-prod
  commonName: {{ .hostname }}
  dnsNames:
  - {{ .hostname }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - {{ .hostname }}
    - http01:
        ingress: my-ingress
      domains:
      - {{ .hostname }}
