# build environment
FROM node:11 as builder
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json package-lock.json /usr/src/app/
RUN npm install --save react-scripts@3.1.1
RUN npm install --save-dev typescript
RUN npm install --save-dev eslint
COPY . /usr/src/app
RUN npm run build

# production environment
FROM nginx:1.17-alpine
COPY --from=builder /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
