version: '3.1'

services:
  jamming:
    privileged: false
    image: jamming:1.0.0
    container_name: jamming
    restart: always
    networks:
      - web
    expose:
      - "80"
    labels:
      - "traefik.backend=jamming"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:jamming.web.cloud.haugom.org"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.default.protocol=http"

networks:
  web:
    external: true
